[package]
name = "memhack"
version = "0.1.0"
authors = ["Jakobzs <31919330+Jakobzs@users.noreply.github.com>"]
edition = "2018"
description = "A memory hacking library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
